version: "3.1"
services:
    studip:
        image: studip:latest
        restart: unless-stopped
        environment:
            USER: 'user'
            PSWD: 'pswd'
            URL: 'https://url.tld'
            INTERVAL: 86400
            HOST: 'mysql'
            DB_USER: root
            DB_PSWD: 'pswddb'
        volumes:
            - studip:/studip/data
        depends_on:
            - mysql

    mysql:
        image: mysql:5.6
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: 'pswddb'
        volumes:
            - mysql:/var/lib/mysql

volumes:
    studip:
        driver: local
    mysql:
        driver: local
