version: "3.1"
services:
    studip:
        image: tiynger/studip-crawler:latest
        restart: unless-stopped
        environment:
            USER: 'user'
            PSWD: 'pswd'
            URL: 'https://url.tld'
            INTERVAL: 86400
        volumes:
            - studip:/studip/data

volumes:
    studip:
        driver: local
